"""Intent OS Kernel — Cognitive Operating System.

A pure Python library that processes user intents through a
Constitutional pipeline with knowledge persistence.

Usage:
    from intent_kernel import Kernel

    kernel = Kernel()
    result = await kernel.process("Quero investir 5000/mês")
    print(result.text)
"""

from intent_kernel.kernel import Kernel
from intent_kernel.types import (
    Mode,
    Domain,
    EpistemicStatus,
    IntentInput,
    IntentOutput,
)

from intent_kernel.iue import IntentUnderstandingEngine, StructuredIntent, IntentQualityIndex
from intent_kernel.cdm import CognitiveDialogueManager, DialogueState, DialogueDecision, CandidateQuestion
from intent_kernel.cpe import CognitivePlanningEngine, ExecutionPlan, PlanStep, PlanQualityIndex
from intent_kernel.cor import CapabilityOrchestrator, ExecutionGraph, RegistryCatalog
from intent_kernel.kom import KnowledgeObject, MemoryClass, KnowledgeNature, KnowledgeState
from intent_kernel.ame import AdaptiveMemoryEngine, MemoryCandidate, MemoryDecision, ContextAssembler
from intent_kernel.bcc import (
    BootstrapCognitiveCortex,
    LocalCognitiveMode,
    CognitiveCapabilityAssessment,
    ProviderConnectionIntent,
    LocalMissionContinuation,
    BootstrapCognitiveResult,
)

from intent_kernel.instructions import (
    PersistentInstruction,
    InstructionScope,
    InstructionType,
    PrecedenceLevel,
    MissionConstraint,
    OutputContract,
    OutputValidationResult,
    CompletionEvidence,
    InstructionViolation,
    PersistentInstructionResolver,
    OutputContractValidator,
    SecretInstructionError,
)

from intent_kernel.runtime import (
    MissionRuntime,
    MissionRuntimeState,
    RuntimeNodeState,
    SideEffectLevel,
    ActionGateDecision,
    FailureCategory,
    VerificationStatus,
    ActionContract,
    ExecutionConfirmationRequest,
    RuntimeNode,
    MissionCheckpoint,
    RuntimeTraceRecord,
    FailureReport,
    MissionRuntimeInstance,
    ActionGate,
    ActionExecutorPort,
    InMemoryActionExecutor,
    RealActionExecutionProhibitedError,
    VerificationGate,
    MissionCompletionGate,
    InMemoryCheckpointRepository,
)

from intent_kernel.tools import (
    ToolStatus,
    ToolOrigin,
    ToolType,
    PermissionScope,
    PermissionDecisionState,
    ToolHealthStatus,
    ToolAuthorizationDecisionState,
    CredentialReference,
    ToolResource,
    CapabilityToolMapping,
    ToolCandidate,
    PermissionDecision,
    DryRunRequest,
    DryRunResult,
    ToolSelectionTrace,
    ToolRegistryPort,
    InMemoryToolRegistry,
    PermissionManager,
    CapabilityRouter,
    ToolAuthorizationGate,
    SecretResolverPort,
    FakeSecretResolver,
    ToolHealthPort,
    InMemoryToolHealthAdapter,
    InMemoryToolAdapter,
    EmailSimulationTool,
    CalendarSimulationTool,
    FilesystemSimulationTool,
    BrowserSimulationTool,
    ToolAccessExecutorAdapter,
)

__version__ = "0.1.0"

__all__ = [
    "Kernel",
    "Mode",
    "Domain",
    "EpistemicStatus",
    "IntentInput",
    "IntentOutput",
    "IntentUnderstandingEngine",
    "StructuredIntent",
    "IntentQualityIndex",
    "CognitiveDialogueManager",
    "DialogueState",
    "DialogueDecision",
    "CandidateQuestion",
    "CognitivePlanningEngine",
    "ExecutionPlan",
    "PlanStep",
    "PlanQualityIndex",
    "CapabilityOrchestrator",
    "ExecutionGraph",
    "RegistryCatalog",
    "KnowledgeObject",
    "MemoryClass",
    "KnowledgeNature",
    "KnowledgeState",
    "AdaptiveMemoryEngine",
    "MemoryCandidate",
    "MemoryDecision",
    "ContextAssembler",
    "BootstrapCognitiveCortex",
    "LocalCognitiveMode",
    "CognitiveCapabilityAssessment",
    "ProviderConnectionIntent",
    "LocalMissionContinuation",
    "BootstrapCognitiveResult",
    "PersistentInstruction",
    "InstructionScope",
    "InstructionType",
    "PrecedenceLevel",
    "MissionConstraint",
    "OutputContract",
    "OutputValidationResult",
    "CompletionEvidence",
    "InstructionViolation",
    "PersistentInstructionResolver",
    "OutputContractValidator",
    "SecretInstructionError",
    "MissionRuntime",
    "MissionRuntimeState",
    "RuntimeNodeState",
    "SideEffectLevel",
    "ActionGateDecision",
    "FailureCategory",
    "VerificationStatus",
    "ActionContract",
    "ExecutionConfirmationRequest",
    "RuntimeNode",
    "MissionCheckpoint",
    "RuntimeTraceRecord",
    "FailureReport",
    "MissionRuntimeInstance",
    "ActionGate",
    "ActionExecutorPort",
    "InMemoryActionExecutor",
    "RealActionExecutionProhibitedError",
    "VerificationGate",
    "MissionCompletionGate",
    "InMemoryCheckpointRepository",
    "ToolStatus",
    "ToolOrigin",
    "ToolType",
    "PermissionScope",
    "PermissionDecisionState",
    "ToolHealthStatus",
    "ToolAuthorizationDecisionState",
    "CredentialReference",
    "ToolResource",
    "CapabilityToolMapping",
    "ToolCandidate",
    "PermissionDecision",
    "DryRunRequest",
    "DryRunResult",
    "ToolSelectionTrace",
    "ToolRegistryPort",
    "InMemoryToolRegistry",
    "PermissionManager",
    "CapabilityRouter",
    "ToolAuthorizationGate",
    "SecretResolverPort",
    "FakeSecretResolver",
    "ToolHealthPort",
    "InMemoryToolHealthAdapter",
    "InMemoryToolAdapter",
    "EmailSimulationTool",
    "CalendarSimulationTool",
    "FilesystemSimulationTool",
    "BrowserSimulationTool",
    "ToolAccessExecutorAdapter",
]
