"""Cognitive Dialogue Manager (CDM) — RFC-0008.

The cognitive decision layer responsible for evaluating StructuredIntents produced by IUE,
determining dialogue state, and selecting the SINGLE highest-impact question to ask
the user, minimizing user friction while maximizing intent clarity.

Architectural Guarantee (RFC-0008):
- Does NOT call LLM Providers directly.
- Does NOT generate final conversational answers.
- Does NOT execute Capabilities or Agents.
- Does NOT mutate Mission state directly or create Missions.
- Never asks questions automatically/blindly — evaluates if it can proceed, if it needs to ask,
  and if asking is worth the user effort.
"""

from __future__ import annotations

import re
import time
import unicodedata
from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import uuid4

from intent_kernel.iue import StructuredIntent


class DialogueState(str, Enum):
    """Possible dialogue decision states evaluated by CDM."""
    READY_TO_EXECUTE = "READY_TO_EXECUTE"
    NEEDS_CONTEXT = "NEEDS_CONTEXT"
    NEEDS_CONFIRMATION = "NEEDS_CONFIRMATION"
    MULTIPLE_VALID_PATHS = "MULTIPLE_VALID_PATHS"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    INSUFFICIENT_INFORMATION = "INSUFFICIENT_INFORMATION"


class PendingDialogueMatchStatus(str, Enum):
    """Whether an utterance is evidence-backed as an answer to the active question."""

    VALID_CONTINUATION = "VALID_CONTINUATION"
    NOT_A_CONTINUATION = "NOT_A_CONTINUATION"
    AMBIGUOUS = "AMBIGUOUS"


@dataclass(frozen=True)
class PendingDialogueMatch:
    """Typed CDM decision for a possible pending-dialogue answer."""

    target_field: str
    candidate_value: Any | None
    match_status: PendingDialogueMatchStatus
    confidence: float
    evidence: tuple[str, ...]
    reason: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "target_field": self.target_field,
            "candidate_value": self.candidate_value,
            "match_status": self.match_status.value,
            "confidence": self.confidence,
            "evidence": list(self.evidence),
            "reason": self.reason,
        }


@dataclass
class CandidateQuestion:
    """A candidate question planned by the Question Planner."""
    question_id: str
    question: str
    expected_iqi_gain: float
    estimated_information_gain: float
    estimated_user_effort: float  # Scale 0.0 (minimal effort) to 1.0 (high cognitive effort)
    reason: str
    target_field: str
    suggested_options: Optional[List[str]] = None

    def calculate_net_value(self) -> float:
        """Calculate net value ratio: high information gain & IQI gain with minimal user effort."""
        effort_discount = 1.0 + (0.5 * self.estimated_user_effort)
        return (self.expected_iqi_gain * (1.0 + self.estimated_information_gain)) / effort_discount

    def to_dict(self) -> Dict[str, Any]:
        return {
            "question_id": self.question_id,
            "question": self.question,
            "expected_iqi_gain": round(self.expected_iqi_gain, 2),
            "estimated_information_gain": round(self.estimated_information_gain, 2),
            "estimated_user_effort": round(self.estimated_user_effort, 2),
            "net_value": round(self.calculate_net_value(), 2),
            "reason": self.reason,
            "target_field": self.target_field,
            "suggested_options": self.suggested_options,
        }


@dataclass
class DialogueDecision:
    """The outcome decision generated by CDM."""
    decision_id: str
    intent_id: str
    state: DialogueState
    can_proceed: bool
    requires_question: bool
    selected_question: Optional[CandidateQuestion]
    candidate_questions: List[CandidateQuestion]
    justification: Dict[str, Any]
    initial_iqi: float
    projected_iqi_after_question: float
    net_value: float

    def to_dict(self) -> Dict[str, Any]:
        return {
            "decision_id": self.decision_id,
            "intent_id": self.intent_id,
            "state": self.state.value if isinstance(self.state, DialogueState) else str(self.state),
            "can_proceed": self.can_proceed,
            "requires_question": self.requires_question,
            "selected_question": self.selected_question.to_dict() if self.selected_question else None,
            "candidate_questions": [q.to_dict() for q in self.candidate_questions],
            "justification": self.justification,
            "initial_iqi": round(self.initial_iqi, 2),
            "projected_iqi_after_question": round(self.projected_iqi_after_question, 2),
            "net_value": round(self.net_value, 2),
        }


@dataclass
class PendingDialogueContext:
    """Persistent context for pending cognitive dialogue questions (RFC-0017.1)."""
    conversation_id: str
    intent_id: str
    dialogue_state: str
    pending_question: str
    target_field: str
    mission_id: Optional[str] = None
    known_context: Dict[str, Any] = field(default_factory=dict)
    missing_context: List[str] = field(default_factory=list)
    asked_at: str = field(default_factory=lambda: time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))
    expires_at: Optional[str] = None
    correlation_id: Optional[str] = None
    schema_version: str = "1.0"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "conversation_id": self.conversation_id,
            "mission_id": self.mission_id,
            "intent_id": self.intent_id,
            "dialogue_state": self.dialogue_state,
            "pending_question": self.pending_question,
            "target_field": self.target_field,
            "known_context": self.known_context,
            "missing_context": self.missing_context,
            "asked_at": self.asked_at,
            "expires_at": self.expires_at,
            "correlation_id": self.correlation_id,
            "schema_version": self.schema_version,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "PendingDialogueContext":
        return cls(
            conversation_id=str(data.get("conversation_id", "")),
            mission_id=data.get("mission_id"),
            intent_id=str(data.get("intent_id", "")),
            dialogue_state=str(data.get("dialogue_state", "WAITING_CONTEXT")),
            pending_question=str(data.get("pending_question", "")),
            target_field=str(data.get("target_field", "")),
            known_context=data.get("known_context") if isinstance(data.get("known_context"), dict) else {},
            missing_context=data.get("missing_context") if isinstance(data.get("missing_context"), list) else [],
            asked_at=str(data.get("asked_at", "")),
            expires_at=data.get("expires_at"),
            correlation_id=data.get("correlation_id"),
            schema_version=str(data.get("schema_version", "1.0")),
        )


@dataclass
class DialogueLearningRecord:
    """Feedback log record for Cognitive Learning Engine (CLE)."""
    record_id: str
    timestamp: float
    question_id: str
    question_text: str
    target_field: str
    user_response: str
    initial_iqi: float
    actual_iqi_after: float
    actual_iqi_gain: float
    expected_iqi_gain: float
    was_helpful: bool

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class CognitiveDialogueManager:
    """Engine responsible for deciding dialogue turns and selecting single best questions."""

    def __init__(self):
        self.learning_log: List[DialogueLearningRecord] = []

    @staticmethod
    def _normalize_answer(text: str) -> str:
        normalized = unicodedata.normalize("NFKD", text.casefold())
        return " ".join(
            "".join(ch for ch in normalized if not unicodedata.combining(ch))
            .strip(" .,!;:")
            .split()
        )

    def match_pending_response(
        self,
        text: str,
        pending: PendingDialogueContext | None,
        structured_intent: StructuredIntent | None = None,
    ) -> PendingDialogueMatch:
        """Classify and type an answer without treating a pending question as a modal lock."""
        if pending is None:
            return PendingDialogueMatch(
                target_field="", candidate_value=None,
                match_status=PendingDialogueMatchStatus.NOT_A_CONTINUATION,
                confidence=1.0, evidence=(), reason="No pending dialogue is active.",
            )

        target = pending.target_field
        normalized = self._normalize_answer(text)
        evidence = (
            f"target_field={target}",
            f"question={pending.pending_question}",
            f"independent_domain={getattr(structured_intent, 'domain', 'unknown')}",
        )
        if not normalized:
            return PendingDialogueMatch(
                target, None, PendingDialogueMatchStatus.AMBIGUOUS, 0.0,
                evidence, "The utterance is empty and cannot be typed safely.",
            )

        # A question or an independently structured request changes subject. It cannot
        # answer a field merely because one of its words resembles a field marker.
        is_question = text.strip().endswith("?") or bool(re.match(
            r"^(qual|quais|como|quando|onde|quem|quanto|quantos|explique|descreva)\b",
            normalized,
        ))
        if is_question:
            return PendingDialogueMatch(
                target, None, PendingDialogueMatchStatus.NOT_A_CONTINUATION, 1.0,
                (*evidence, "independent_question_shape"),
                "The utterance has the linguistic shape of a new independent request.",
            )

        patterns: dict[str, tuple[tuple[str, Any], ...]] = {
            "recurrence": (
                (r"(?:o aporte (?:sera )?|sera |vai ser |com (?:aportes? )?|pretendo aportar )?(?:mensal|mensais|todo mes|por mes)", "mensal"),
                (r"(?:o aporte (?:sera )?|sera |vai ser )?(?:unico|uma vez|pontual)", "único"),
            ),
            "investment_frequency": (
                (r"(?:o aporte (?:sera )?|sera |vai ser |com (?:aportes? )?|pretendo aportar )?(?:mensal|mensais|todo mes|por mes)", "mensal"),
                (r"(?:o aporte (?:sera )?|sera |vai ser )?(?:unico|uma vez|pontual)", "único"),
            ),
            "goal": (
                (r"(?:meu objetivo (?:e |seria )?|para |quero investir para )?aposentadoria", "aposentadoria"),
                (r"(?:meu objetivo (?:e |seria )?|para |quero investir para )?(?:formar |criar )?(?:uma )?reserva(?: de emergencia)?", "reserva de emergência"),
                (r"(?:meu objetivo (?:e |seria )?|para |quero investir para )?(?:comprar |adquirir )(?:uma |um )?(?:casa|imovel)", "compra de imóvel"),
            ),
            "risk_profile": (
                (r"(?:sou |meu perfil (?:e |seria )?|prefiro (?:um perfil )?)?moderado", "moderado"),
                (r"(?:sou |meu perfil (?:e |seria )?|prefiro (?:um perfil )?)?conservador", "conservador"),
                (r"(?:sou |meu perfil (?:e |seria )?|prefiro (?:um perfil )?)?(?:arrojado|agressivo)", "arrojado"),
            ),
            "liquidity": (
                (r"(?:preciso de )?liquidez imediata", "liquidez imediata"),
                (r"(?:nao preciso de |sem necessidade de )liquidez(?: imediata)?", "sem necessidade de liquidez imediata"),
                (r"posso manter aplicado(?: pelo prazo)?", "sem necessidade de liquidez imediata"),
            ),
            "platform": (
                (r"(?:a plataforma (?:e |sera )?)?android", "Android"),
                (r"(?:a plataforma (?:e |sera )?)?ios", "iOS"),
                (r"(?:a plataforma (?:e |sera )?)?web", "Web"),
                (r"(?:a plataforma (?:e |sera )?)?windows", "Windows"),
            ),
            "purpose": (
                (r"(?:a finalidade (?:e |sera )?|para )?(?:controle de )?estoque", "controle de estoque"),
                (r"(?:a finalidade (?:e |sera )?|para )?(?:controle de )?vendas", "controle de vendas"),
                (r"(?:a finalidade (?:e |sera )?|para )?(?:gestao de )?clientes", "gestão de clientes"),
                (r"(?:a finalidade (?:e |sera )?|para )?(?:gestao de )?manutencao", "gestão de manutenção"),
            ),
            "connectivity": (
                (r"(?:precisa funcionar |funcionara |sera )?offline", "offline"),
                (r"(?:precisa funcionar |funcionara |sera )?(?:apenas )?online", "online"),
            ),
            "pricing": (
                (r"(?:sera |versao )?(?:gratuita|gratuito|gratis)", "gratuita"),
                (r"(?:sera |versao )?(?:paga|pago|assinatura)", "paga"),
            ),
        }

        if target == "amount":
            amount_match = re.fullmatch(
                r"(?:tenho |o valor (?:e |seria )?|quero investir )?(?:r\$\s*)?(\d+(?:[.,]\d+)?)\s*(mil|k|reais?)?",
                normalized,
            )
            if amount_match:
                amount = float(amount_match.group(1).replace(",", "."))
                if amount_match.group(2) in {"mil", "k"}:
                    amount *= 1000
                return PendingDialogueMatch(
                    target, amount, PendingDialogueMatchStatus.VALID_CONTINUATION,
                    0.98, (*evidence, "typed_money_value"),
                    "A complete amount answer was extracted for the requested field.",
                )
        elif target == "time_horizon":
            horizon = re.fullmatch(
                r"(?:por |pretendo investir por |quero investir por )?(\d+|um|dois|tres|quatro|cinco|dez) (anos?|meses?)",
                normalized,
            )
            if horizon:
                value = f"{horizon.group(1)} {horizon.group(2)}"
                return PendingDialogueMatch(
                    target, value, PendingDialogueMatchStatus.VALID_CONTINUATION,
                    0.98, (*evidence, "typed_duration_value"),
                    "A complete duration answer was extracted for the requested field.",
                )
        else:
            for pattern, value in patterns.get(target, ()):
                if re.fullmatch(pattern, normalized):
                    return PendingDialogueMatch(
                        target, value, PendingDialogueMatchStatus.VALID_CONTINUATION,
                        0.98, (*evidence, "field_specific_full_match"),
                        "The complete utterance has a valid answer shape and typed value.",
                    )

        # A sentence with its own subject/predicate is evidence of a new topic, while
        # a short fragment remains ambiguous rather than being guessed into context.
        tokens = normalized.split()
        new_subject = len(tokens) >= 4 and bool(re.match(
            r"^(minha|meu|o|a|este|esta|esse|essa)\b", normalized
        ))
        if new_subject:
            return PendingDialogueMatch(
                target, None, PendingDialogueMatchStatus.NOT_A_CONTINUATION, 0.95,
                (*evidence, "independent_subject_predicate"),
                "The utterance introduces an independent subject and no typed field answer.",
            )
        return PendingDialogueMatch(
            target, None, PendingDialogueMatchStatus.AMBIGUOUS, 0.4,
            (*evidence, "no_typed_value"),
            "No plausible typed value can be extracted without guessing.",
        )

    def evaluate(
        self,
        structured_intent: StructuredIntent,
        session_context: Optional[Dict[str, Any]] = None
    ) -> DialogueDecision:
        """Evaluate a StructuredIntent and return the dialogue decision."""
        decision_id = f"cdm_{uuid4().hex[:8]}"
        ctx = session_context or {}

        # 1. Extract IQI metrics
        iqi_dict = structured_intent.intent_quality_index or {}
        initial_iqi = iqi_dict.get("overall_score", structured_intent.confidence)

        # 2. Extract known context keywords to prevent redundant questions
        known_facts = [k.lower() for k in structured_intent.known_context]
        known_provenance = structured_intent.known_context_provenance or []
        user_profile = ctx.get("user_profile") or ctx.get("profile") or {}

        # 3. Generate candidate questions using Question Planner
        raw_candidates = self._plan_candidate_questions(structured_intent, user_profile=user_profile)

        # 4. Filter out redundant questions (if information is already in memory or profile)
        filtered_candidates = self._filter_known_context(
            raw_candidates, known_facts, known_provenance, user_profile
        )

        # 5. Rank remaining candidate questions by Net Value (IQI gain / user effort)
        ranked_candidates = sorted(
            filtered_candidates, key=lambda q: q.calculate_net_value(), reverse=True
        )

        # 6. Evaluate State and Selection Strategy
        selected_question: Optional[CandidateQuestion] = None
        state = DialogueState.READY_TO_EXECUTE
        can_proceed = True
        requires_question = False

        # Threshold logic: if IQI is high enough (>= 0.75) AND no candidates or no critical missing context
        if initial_iqi >= 0.75 and (not ranked_candidates or not structured_intent.missing_context):
            state = DialogueState.READY_TO_EXECUTE
            can_proceed = True
            requires_question = False
            selected_question = None
        else:
            # Determine specific non-ready state
            if structured_intent.confidence < 0.60 and structured_intent.domain == "general":
                state = DialogueState.LOW_CONFIDENCE
            elif len(structured_intent.raw_input.split()) <= 3 and structured_intent.domain in ["general", "coding"]:
                state = DialogueState.INSUFFICIENT_INFORMATION
            elif structured_intent.domain == "coding" and any("múltiplas" in a.lower() or "trajetórias" in a.lower() or "plataforma" in a.lower() for a in structured_intent.ambiguities):
                state = DialogueState.MULTIPLE_VALID_PATHS
            elif structured_intent.requires_confirmation and initial_iqi >= 0.70:
                state = DialogueState.NEEDS_CONFIRMATION
            else:
                state = DialogueState.NEEDS_CONTEXT

            if ranked_candidates:
                selected_question = ranked_candidates[0]
                can_proceed = False
                requires_question = True
            else:
                # If all candidate questions were filtered out by known context or non-material,
                # we can proceed to execution!
                state = DialogueState.READY_TO_EXECUTE
                can_proceed = True
                requires_question = False
                selected_question = None

        # 7. Calculate Projected IQI & Justifications
        projected_iqi = initial_iqi
        net_val = 0.0
        if selected_question:
            projected_iqi = min(1.0, initial_iqi + selected_question.expected_iqi_gain)
            net_val = selected_question.calculate_net_value()

        justification = self._build_justification(
            state=state,
            initial_iqi=initial_iqi,
            selected_question=selected_question,
            raw_candidates=raw_candidates,
            filtered_candidates=filtered_candidates,
            ranked_candidates=ranked_candidates,
            structured_intent=structured_intent,
        )

        return DialogueDecision(
            decision_id=decision_id,
            intent_id=structured_intent.intent_id,
            state=state,
            can_proceed=can_proceed,
            requires_question=requires_question,
            selected_question=selected_question,
            candidate_questions=ranked_candidates,
            justification=justification,
            initial_iqi=initial_iqi,
            projected_iqi_after_question=projected_iqi,
            net_value=net_val,
        )

    def _plan_candidate_questions(
        self, intent: StructuredIntent, user_profile: Optional[Dict[str, Any]] = None
    ) -> List[CandidateQuestion]:
        """Question Planner: Generates candidate questions based on domain and missing context."""
        candidates: List[CandidateQuestion] = []
        domain = intent.domain
        text_lower = intent.raw_input.lower()
        user_prof = user_profile or {}

        if domain == "finance":
            # Amount candidate
            has_amount = any("montante" in k.lower() or "r$" in k.lower() for k in intent.known_context)
            if not has_amount:
                candidates.append(CandidateQuestion(
                    question_id=f"q_fin_amount_{uuid4().hex[:4]}",
                    question="Qual é o montante financeiro (valor em R$) que você pretende investir?",
                    expected_iqi_gain=0.35,
                    estimated_information_gain=0.80,
                    estimated_user_effort=0.20,
                    reason="Identificar a escala do investimento para filtrar produtos adequados.",
                    target_field="amount",
                    suggested_options=["R$ 5.000", "R$ 10.000", "R$ 25.000", "Outro valor"]
                ))

            # Goal candidate (Single variable: Objetivo)
            has_goal = any("objetivo" in k.lower() for k in intent.known_context)
            if not has_goal and "financial_goal" not in user_prof:
                amount_str = "este valor"
                if "23.500" in text_lower or "23500" in text_lower:
                    amount_str = "seus R$ 23.500"
                candidates.append(CandidateQuestion(
                    question_id=f"q_fin_goal_{uuid4().hex[:4]}",
                    question=f"Para alocarmos {amount_str} com máxima precisão, qual é o seu objetivo principal com este investimento?",
                    expected_iqi_gain=0.35,
                    estimated_information_gain=0.80,
                    estimated_user_effort=0.20,
                    reason="Determinar o objetivo estratégico para definir a classe de ativos ideal.",
                    target_field="financial_goal",
                    suggested_options=[
                        "Reserva de Emergência",
                        "Aposentadoria / Longo prazo",
                        "Compra de Imóvel / Bem",
                        "Multiplicação de Patrimônio"
                    ]
                ))

            # Horizon / Prazo candidate (Single variable: Prazo)
            has_horizon = any("horizonte" in k.lower() or "prazo" in k.lower() for k in intent.known_context)
            if not has_horizon and "horizon" not in user_prof:
                candidates.append(CandidateQuestion(
                    question_id=f"q_fin_horizon_{uuid4().hex[:4]}",
                    question="Qual é o horizonte de tempo previsto em que você pretende resgatar ou utilizar esses recursos?",
                    expected_iqi_gain=0.28,
                    estimated_information_gain=0.70,
                    estimated_user_effort=0.20,
                    reason="Definir o prazo de maturação adequado para os produtos de investimento.",
                    target_field="horizon",
                    suggested_options=["Curto prazo (até 1 ano)", "Médio prazo (1 a 3 anos)", "Longo prazo (5+ anos)"]
                ))

            # Liquidity candidate (Single variable: Liquidez)
            has_liquidity = any("liquidez" in k.lower() for k in intent.known_context)
            if not has_liquidity and "liquidity_preference" not in user_prof:
                candidates.append(CandidateQuestion(
                    question_id=f"q_fin_liquidity_{uuid4().hex[:4]}",
                    question="Você necessita de liquidez imediata (resgate diário) ou pode manter o recurso aplicado por prazo fixo?",
                    expected_iqi_gain=0.25,
                    estimated_information_gain=0.65,
                    estimated_user_effort=0.15,
                    reason="Avaliar a restrição de liquidez nos veículos financeiros recomendados.",
                    target_field="liquidity_preference",
                    suggested_options=["Liquidez Diária (D+0/D+1)", "Prazo Fico / Carência"]
                ))

            # Risk Profile candidate (Single variable: Risco)
            has_risk = any("perfil de risco" in k.lower() or "conservador" in k.lower() for k in intent.known_context)
            if not has_risk and "risk_tolerance" not in user_prof:
                candidates.append(CandidateQuestion(
                    question_id=f"q_fin_risk_{uuid4().hex[:4]}",
                    question="Qual é o seu perfil de risco para este investimento (conservador, moderado ou arrojado)?",
                    expected_iqi_gain=0.22,
                    estimated_information_gain=0.60,
                    estimated_user_effort=0.15,
                    reason="Garantir tolerância adequada à volatilidade do produto recomendado.",
                    target_field="risk_tolerance",
                    suggested_options=["Conservador (Preservação)", "Moderado (Equilibrado)", "Arrojado (Busca Rentabilidade)"]
                ))

            # Recurrence candidate
            has_recurrence = any("aporte" in k.lower() or "recorrente" in k.lower() for k in intent.known_context)
            if not has_recurrence and "mensal" not in text_lower:
                candidates.append(CandidateQuestion(
                    question_id=f"q_fin_recurrence_{uuid4().hex[:4]}",
                    question="Este investimento será um aporte único ou você pretende realizar aportes mensais?",
                    expected_iqi_gain=0.12,
                    estimated_information_gain=0.40,
                    estimated_user_effort=0.15,
                    reason="Ajustar projeções de rentabilidade e fluxo de caixa.",
                    target_field="recurrence",
                    suggested_options=["Aporte Único", "Aportes Mensais Recorrentes"]
                ))

        elif domain in ["coding", "general"] and ("aplicativo" in text_lower or "app" in text_lower or "sistema" in text_lower):
            # Application architecture candidate (No rigid tech like React hardcoded unless in context)
            candidates.append(CandidateQuestion(
                question_id=f"q_code_app_scope_{uuid4().hex[:4]}",
                question=(
                    "Qual é a finalidade principal do aplicativo que você deseja criar "
                    "e para qual plataforma (ex: web, mobile ou desktop)?"
                ),
                expected_iqi_gain=0.45,
                estimated_information_gain=0.90,
                estimated_user_effort=0.35,
                reason="Reduzir incerteza estrutural em pedidos genéricos de criação de software.",
                target_field="app_architecture_and_purpose",
                suggested_options=["Web App", "Mobile App", "Desktop App", "API Service Backend"]
            ))

        # Generic missing context fallbacks
        for item in intent.missing_context:
            target_slug = item.split()[0].lower()
            # Avoid duplicating if already planned
            if not any(c.target_field == target_slug for c in candidates):
                candidates.append(CandidateQuestion(
                    question_id=f"q_missing_{target_slug}_{uuid4().hex[:4]}",
                    question=f"Para prosseguirmos com precisão, qual é o seu {item.lower()}?",
                    expected_iqi_gain=0.25,
                    estimated_information_gain=0.60,
                    estimated_user_effort=0.25,
                    reason=f"Esclarecer lacuna explícita identificada no IUE: {item}",
                    target_field=target_slug
                ))

        return candidates

    def _filter_known_context(
        self,
        candidates: List[CandidateQuestion],
        known_facts: List[str],
        known_provenance: List[Dict[str, str]],
        user_profile: Dict[str, Any]
    ) -> List[CandidateQuestion]:
        """Filter out candidate questions if the information is already known in memory or profile."""
        filtered: List[CandidateQuestion] = []

        profile_str = str(user_profile).lower()

        for q in candidates:
            target = q.target_field.lower()

            # Memory checks
            is_known = False

            if target == "financial_goal":
                if any("objetivo" in f for f in known_facts) or "financial_goal" in user_profile or "goal" in user_profile:
                    is_known = True

            elif target == "horizon":
                if any("horizonte" in f or "prazo" in f for f in known_facts) or "horizon" in user_profile or "timeframe" in user_profile:
                    is_known = True

            elif target == "liquidity_preference":
                if any("liquidez" in f for f in known_facts) or "liquidity_preference" in user_profile or "liquidity" in user_profile:
                    is_known = True

            elif target == "risk_tolerance":
                if any("perfil de risco" in f or "conservador" in f or "arrojado" in f for f in known_facts):
                    is_known = True
                elif "risk_tolerance" in user_profile or "risk" in user_profile:
                    is_known = True

            elif target == "amount":
                if any("montante" in f or "r$" in f for f in known_facts):
                    is_known = True
                elif "amount" in user_profile:
                    is_known = True

            elif target == "app_architecture_and_purpose":
                if any("plataforma" in f or "arquitetura" in f or "web app" in f for f in known_facts):
                    is_known = True

            if not is_known:
                filtered.append(q)

        return filtered

    def _build_justification(
        self,
        state: DialogueState,
        initial_iqi: float,
        selected_question: Optional[CandidateQuestion],
        raw_candidates: List[CandidateQuestion],
        filtered_candidates: List[CandidateQuestion],
        ranked_candidates: List[CandidateQuestion],
        structured_intent: StructuredIntent
    ) -> Dict[str, Any]:
        """Build internal cognitive justification explaining selections and rejections."""
        justification: Dict[str, Any] = {
            "eval_state": state.value if isinstance(state, DialogueState) else str(state),
            "initial_iqi_score": round(initial_iqi, 2),
            "total_candidates_generated": len(raw_candidates),
            "candidates_after_memory_filter": len(filtered_candidates),
            "selection_reasoning": "",
            "discarded_candidates_reasons": []
        }

        if state == DialogueState.READY_TO_EXECUTE:
            if not raw_candidates:
                justification["selection_reasoning"] = (
                    "Nenhuma pergunta necessária. A intenção possui clareza e completude suficientes (IQI alto) "
                    "para geração da Missão."
                )
            else:
                justification["selection_reasoning"] = (
                    "Contexto prévio suficiente encontrado em memória/perfil. Perguntas redundantes foram "
                    "filtradas, permitindo execução direta."
                )
        elif selected_question:
            justification["selection_reasoning"] = (
                f"Selecionada a pergunta '{selected_question.question_id}' ({selected_question.target_field}) "
                f"pois apresenta o maior valor líquido de ganho de IQI (+{selected_question.expected_iqi_gain:.2f}) "
                f"com atrito estimado baixo ({selected_question.estimated_user_effort:.2f})."
            )

            # Document discarded candidates
            for q in raw_candidates:
                if q.question_id == selected_question.question_id:
                    continue
                if q not in filtered_candidates:
                    justification["discarded_candidates_reasons"].append({
                        "question_id": q.question_id,
                        "target_field": q.target_field,
                        "reason": "Descartada: Informação já existente na memória da sessão / perfil do usuário."
                    })
                else:
                    justification["discarded_candidates_reasons"].append({
                        "question_id": q.question_id,
                        "target_field": q.target_field,
                        "reason": (
                            f"Descartada: Valor líquido de IQI ({q.calculate_net_value():.2f}) inferior "
                            f"à pergunta selecionada ({selected_question.calculate_net_value():.2f})."
                        )
                    })

        return justification

    def record_feedback(
        self,
        question_id: str,
        question_text: str,
        target_field: str,
        user_response: str,
        initial_iqi: float,
        actual_iqi_after: float,
        expected_iqi_gain: float
    ) -> DialogueLearningRecord:
        """Record feedback log for Cognitive Learning Engine (CLE)."""
        actual_gain = round(actual_iqi_after - initial_iqi, 2)
        was_helpful = actual_gain >= (expected_iqi_gain * 0.5)

        record = DialogueLearningRecord(
            record_id=f"clr_{uuid4().hex[:8]}",
            timestamp=time.time(),
            question_id=question_id,
            question_text=question_text,
            target_field=target_field,
            user_response=user_response,
            initial_iqi=initial_iqi,
            actual_iqi_after=actual_iqi_after,
            actual_iqi_gain=actual_gain,
            expected_iqi_gain=expected_iqi_gain,
            was_helpful=was_helpful,
        )
        self.learning_log.append(record)
        return record
