"""Cognitive Planning Engine (CPE) — RFC-0009.

Transforms a structured, understood intent (StructuredIntent) into a verifiable,
dependency-aware, capability-first ExecutionPlan without executing side-effects.
"""

from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import uuid4

from intent_kernel.cdm import DialogueDecision, DialogueState
from intent_kernel.iue import StructuredIntent
from intent_kernel.time_utils import utc_iso


@dataclass
class PlanStep:
    """Represents a single atomic step within an ExecutionPlan."""

    step_id: str
    objective: str
    action_type: str  # e.g., "retrieve", "analyze", "calculate", "synthesize", "validate", "external_action"
    inputs: Dict[str, Any] = field(default_factory=dict)
    expected_output: str = ""
    dependencies: List[str] = field(default_factory=list)  # Step IDs required before execution
    required_capabilities: List[str] = field(default_factory=list)
    candidate_agents: List[str] = field(default_factory=list)
    risk_level: str = "low"  # "low", "medium", "high", "critical"
    reversibility: str = "reversible"  # "reversible", "partially_reversible", "irreversible"
    requires_confirmation: bool = False
    validation: List[str] = field(default_factory=list)
    retry_policy: Dict[str, Any] = field(default_factory=lambda: {"max_retries": 2, "backoff": "exponential"})
    status: str = "pending"  # "pending", "ready", "blocked", "running", "waiting_user", "completed", "failed", "skipped"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class PlanQualityIndex:
    """Plan Quality Index (PQI) evaluating structural validity and safety of an ExecutionPlan.
    
    Difference from IQI:
    - IQI (Intent Quality Index): Measures how well the system understands the human intent.
    - PQI (Plan Quality Index): Measures how complete, safe, feasible, and verifiable the generated execution plan is.
    """

    goal_alignment: float = 1.0
    completeness: float = 1.0
    feasibility: float = 1.0
    dependency_integrity: float = 1.0
    risk_awareness: float = 1.0
    validation_coverage: float = 1.0
    overall_score: float = 1.0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class ExecutionPlan:
    """Structured, declarative execution plan generated by the CPE."""

    plan_id: str
    intent_id: str
    goal: str
    status: str = "draft"  # "draft", "ready", "blocked", "failed", "completed", "replanned"
    mission_candidate_id: Optional[str] = None
    assumptions: List[Dict[str, Any]] = field(default_factory=list)
    constraints: List[str] = field(default_factory=list)
    steps: List[PlanStep] = field(default_factory=list)
    dependencies: List[Dict[str, Any]] = field(default_factory=list)  # [{"from": "step_1", "to": "step_2"}]
    required_capabilities: List[str] = field(default_factory=list)
    candidate_agents: List[str] = field(default_factory=list)
    provider_requirements: Dict[str, Any] = field(default_factory=dict)
    confirmation_points: List[Dict[str, Any]] = field(default_factory=list)
    validation_rules: List[str] = field(default_factory=list)
    rollback_strategy: Optional[Dict[str, Any]] = None
    confidence: float = 0.85
    provenance: List[Dict[str, Any]] = field(default_factory=list)
    plan_quality_index: PlanQualityIndex = field(default_factory=PlanQualityIndex)
    created_at: str = field(default_factory=utc_iso)

    def to_dict(self) -> Dict[str, Any]:
        res = asdict(self)
        res["steps"] = [s.to_dict() if hasattr(s, "to_dict") else s for s in self.steps]
        res["plan_quality_index"] = (
            self.plan_quality_index.to_dict()
            if hasattr(self.plan_quality_index, "to_dict")
            else self.plan_quality_index
        )
        return res


class CognitivePlanningEngine:
    """Engine responsible for decomposing understood intents into structured execution plans.
    
    Enforces:
    - Capability-first step design (no hardcoded provider/agent execution)
    - Strict confirmation gates for external/irreversible actions
    - Circular dependency detection
    - PQI evaluation
    - Graceful handling of non-READY dialogue states
    """

    DEFAULT_CAPABILITIES = [
        "retrieval.financial_context",
        "modeling.allocation_scenarios",
        "analysis.risk_evaluation",
        "synthesis.recommendation",
        "validation.goal_alignment",
        "code.architecture_design",
        "code.scaffold_generation",
        "external.communication",
        "research.information_gathering",
        "research.comparative_analysis",
    ]

    DEFAULT_AGENTS = ["core_agent", "atlas", "logos", "code_agent", "financial_agent"]

    def create_plan(
        self,
        intent: StructuredIntent,
        session_context: Optional[Dict[str, Any]] = None,
        dialogue_decision: Optional[DialogueDecision] = None,
        available_capabilities: Optional[List[str]] = None,
        available_agents: Optional[List[str]] = None,
        constraints: Optional[List[str]] = None,
        policies: Optional[List[str]] = None,
    ) -> ExecutionPlan:
        """Generates an ExecutionPlan from a StructuredIntent."""
        plan_id = f"plan_{uuid4().hex[:8]}"
        session_context = session_context or {}
        caps = available_capabilities or self.DEFAULT_CAPABILITIES
        agents = available_agents or self.DEFAULT_AGENTS
        all_constraints = list(set(intent.constraints + (constraints or [])))

        # Rule 15: If dialogue decision exists and is NOT ready to execute, return a blocked draft plan
        if dialogue_decision and not dialogue_decision.can_proceed:
            plan = ExecutionPlan(
                plan_id=plan_id,
                intent_id=intent.intent_id,
                goal=intent.goal,
                status="blocked",
                assumptions=[{"text": "Diálogo pendente com o usuário", "provenance": "CDM"}],
                constraints=all_constraints,
                steps=[],
                dependencies=[],
                required_capabilities=[],
                candidate_agents=[],
                provider_requirements={"reasoning": "low", "context_window": "small"},
                confirmation_points=[
                    {
                        "gate_id": "gate_dialogue_pending",
                        "type": "clarification_required",
                        "reason": f"Aguardando esclarecimento do usuário (Estado CDM: {dialogue_decision.state.value})",
                        "question": (
                            dialogue_decision.selected_question.question
                            if dialogue_decision.selected_question
                            else "Informação insuficiente para prosseguir."
                        ),
                    }
                ],
                validation_rules=["Obter esclarecimento do usuário antes do planejamento."],
                confidence=intent.confidence * 0.5,
                provenance=[
                    {"fact": intent.goal, "origin": "IUE", "type": "FACT"},
                    {"fact": f"CDM State: {dialogue_decision.state.value}", "origin": "CDM", "type": "POLICY"},
                ],
            )
            plan.plan_quality_index = self.calculate_pqi(plan)
            return plan

        # Generate domain-specific steps based on capabilities and intent
        steps: List[PlanStep] = []
        deps: List[Dict[str, Any]] = []
        confirmation_points: List[Dict[str, Any]] = []
        assumptions: List[Dict[str, Any]] = []
        provenance: List[Dict[str, Any]] = [
            {"fact": f"Goal: {intent.goal}", "origin": "IUE", "type": "FACT"},
            {"fact": f"Domain: {intent.domain}", "origin": "IUE", "type": "FACT"},
        ]

        for fact in intent.known_context:
            provenance.append({"fact": fact, "origin": "IUE", "type": "FACT"})

        for ass in intent.assumptions:
            assumptions.append({"text": ass, "provenance": "IUE"})

        text_lower = intent.raw_input.lower()

        # CASE A: Financial Investment
        if intent.domain == "finance" or "invest" in text_lower or "23.500" in text_lower:
            steps, deps, confirmation_points = self._plan_finance_steps(intent, session_context, caps, agents)

        # CASE C: External Communication (e.g. Email)
        elif "e-mail" in text_lower or "email" in text_lower or "enviar" in text_lower or "comunicar" in text_lower:
            steps, deps, confirmation_points = self._plan_communication_steps(intent, caps, agents)

        # CASE D: Comparative Research
        elif "pesquis" in text_lower or "compar" in text_lower or "alternativas" in text_lower:
            steps, deps, confirmation_points = self._plan_comparative_research_steps(intent, caps, agents)

        # CASE B: Software App Creation / Coding
        elif intent.domain == "coding" or "aplicativo" in text_lower or "app" in text_lower:
            steps, deps, confirmation_points = self._plan_software_steps(intent, caps, agents)

        # Default fallback plan
        else:
            steps, deps, confirmation_points = self._plan_generic_steps(intent, caps, agents)

        # Collect overall required capabilities and candidate agents across steps
        req_caps = sorted(list({cap for step in steps for cap in step.required_capabilities}))
        cand_agents = sorted(list({ag for step in steps for ag in step.candidate_agents}))

        # Provider requirements (abstract specification, not vendor specific)
        provider_reqs = {
            "reasoning": "high" if len(steps) > 3 or any(s.risk_level in ["high", "critical"] for s in steps) else "medium",
            "context_window": "medium",
            "tool_use": True,
            "structured_output": True,
            "privacy": "standard",
        }

        validation_rules = [
            "Todas as premissas devem estar explicitamente documentadas.",
            "Cálculos e projeções devem ser logicamente consistentes.",
            "Nenhuma informação ausente deve ser inventada.",
            "Riscos e reversibilidade de cada etapa devem ser respeitados.",
        ]

        if confirmation_points:
            validation_rules.append("Etapas com confirmação do usuário exigem validação prévia antes do disparo.")

        # Construct ExecutionPlan
        plan = ExecutionPlan(
            plan_id=plan_id,
            intent_id=intent.intent_id,
            goal=intent.goal,
            status="ready",
            mission_candidate_id=f"mission_{uuid4().hex[:6]}",
            assumptions=assumptions,
            constraints=all_constraints,
            steps=steps,
            dependencies=deps,
            required_capabilities=req_caps,
            candidate_agents=cand_agents,
            provider_requirements=provider_reqs,
            confirmation_points=confirmation_points,
            validation_rules=validation_rules,
            rollback_strategy={
                "type": "checkpoint_restore",
                "description": "Se ocorrer falha em etapas críticas, reverter estado para o último checkpoint validado.",
            },
            confidence=min(0.95, max(0.60, intent.confidence)),
            provenance=provenance,
        )

        # Check for circular dependencies
        if self.detect_cycles(plan.steps):
            plan.status = "blocked"
            plan.confirmation_points.append({
                "gate_id": "gate_circular_dependency",
                "type": "invalid_plan",
                "reason": "Ciclo de dependência inválido detectado no grafo do plano."
            })

        # Check for missing capabilities
        missing_caps = [c for c in req_caps if c not in caps and not c.startswith("retrieval") and not c.startswith("code")]
        if missing_caps:
            plan.status = "blocked"
            plan.assumptions.append({"text": f"Capacidade ausente detectada: {missing_caps}", "provenance": "CPE"})

        plan.plan_quality_index = self.calculate_pqi(plan)
        return plan

    def detect_cycles(self, steps: List[PlanStep]) -> bool:
        """Detects circular dependencies in step dependency graph using DFS."""
        graph: Dict[str, List[str]] = {s.step_id: s.dependencies for s in steps}
        visited: Dict[str, int] = {s.step_id: 0 for s in steps}  # 0: unvisited, 1: visiting, 2: visited

        def dfs(node: str) -> bool:
            if visited.get(node) == 1:
                return True  # Cycle detected
            if visited.get(node) == 2:
                return False
            visited[node] = 1
            for dep in graph.get(node, []):
                if dep in graph and dfs(dep):
                    return True
            visited[node] = 2
            return False

        for step in steps:
            if visited[step.step_id] == 0:
                if dfs(step.step_id):
                    return True
        return False

    def calculate_pqi(self, plan: ExecutionPlan) -> PlanQualityIndex:
        """Calculates Plan Quality Index (PQI)."""
        if plan.status == "blocked" and not plan.steps:
            return PlanQualityIndex(
                goal_alignment=0.50,
                completeness=0.30,
                feasibility=0.50,
                dependency_integrity=1.0,
                risk_awareness=0.80,
                validation_coverage=0.40,
                overall_score=0.42,
            )

        # 1. Goal Alignment
        goal_alignment = 0.95 if plan.steps else 0.50

        # 2. Completeness
        completeness = 0.90 if len(plan.steps) >= 3 else 0.70

        # 3. Feasibility
        feasibility = 0.95 if plan.status == "ready" else 0.40

        # 4. Dependency Integrity
        has_cycle = self.detect_cycles(plan.steps)
        dependency_integrity = 0.0 if has_cycle else 1.0

        # 5. Risk Awareness
        high_risk_steps = [s for s in plan.steps if s.risk_level in ["high", "critical"] or s.reversibility == "irreversible"]
        unprotected = [s for s in high_risk_steps if not s.requires_confirmation]
        risk_awareness = 0.50 if unprotected else 0.95

        # 6. Validation Coverage
        steps_with_val = [s for s in plan.steps if s.validation]
        validation_coverage = len(steps_with_val) / len(plan.steps) if plan.steps else 0.50

        overall = (
            (goal_alignment * 0.25)
            + (completeness * 0.20)
            + (feasibility * 0.20)
            + (dependency_integrity * 0.15)
            + (risk_awareness * 0.10)
            + (validation_coverage * 0.10)
        )

        return PlanQualityIndex(
            goal_alignment=round(goal_alignment, 2),
            completeness=round(completeness, 2),
            feasibility=round(feasibility, 2),
            dependency_integrity=round(dependency_integrity, 2),
            risk_awareness=round(risk_awareness, 2),
            validation_coverage=round(validation_coverage, 2),
            overall_score=round(overall, 2),
        )

    def replan(
        self,
        existing_plan: ExecutionPlan,
        failed_step_id: str,
        failure_reason: str,
        new_context: Optional[Dict[str, Any]] = None,
    ) -> ExecutionPlan:
        """Adapts an existing plan after a step failure without resetting completed steps."""
        updated_steps: List[PlanStep] = []
        new_context = new_context or {}

        for step in existing_plan.steps:
            if step.step_id == failed_step_id:
                # Mark failed step
                step.status = "failed"
                updated_steps.append(step)

                # Insert recovery/alternative step
                recovery_step = PlanStep(
                    step_id=f"{failed_step_id}_recovery",
                    objective=f"Recuperar da falha na etapa {failed_step_id}: {failure_reason}",
                    action_type="analyze_and_fallback",
                    inputs={"failed_step": failed_step_id, "reason": failure_reason, "context": new_context},
                    expected_output="Estratégia alternativa definida e validada.",
                    dependencies=[failed_step_id],
                    required_capabilities=step.required_capabilities,
                    candidate_agents=step.candidate_agents,
                    risk_level="medium",
                    reversibility="reversible",
                    requires_confirmation=True,
                    validation=["Verificar se a alternativa contorna a falha."],
                    status="pending",
                )
                updated_steps.append(recovery_step)
            elif failed_step_id in step.dependencies:
                # Update downstream dependencies to point to recovery step
                new_deps = [d for d in step.dependencies if d != failed_step_id] + [f"{failed_step_id}_recovery"]
                step.dependencies = new_deps
                step.status = "blocked"
                updated_steps.append(step)
            else:
                updated_steps.append(step)

        replanned_plan = ExecutionPlan(
            plan_id=f"plan_re_{uuid4().hex[:6]}",
            intent_id=existing_plan.intent_id,
            goal=existing_plan.goal,
            status="replanned",
            mission_candidate_id=existing_plan.mission_candidate_id,
            assumptions=existing_plan.assumptions + [{"text": f"Replanejamento ativado devido a falha na etapa {failed_step_id}", "provenance": "CPE"}],
            constraints=existing_plan.constraints,
            steps=updated_steps,
            dependencies=[{"from": s.step_id, "to": dep} for s in updated_steps for dep in s.dependencies],
            required_capabilities=existing_plan.required_capabilities,
            candidate_agents=existing_plan.candidate_agents,
            provider_requirements=existing_plan.provider_requirements,
            confirmation_points=existing_plan.confirmation_points + [
                {
                    "gate_id": f"gate_replan_{failed_step_id}",
                    "type": "replan_confirmation",
                    "reason": f"Falha na etapa {failed_step_id}. Replanejamento requer validação.",
                }
            ],
            validation_rules=existing_plan.validation_rules,
            rollback_strategy=existing_plan.rollback_strategy,
            confidence=max(0.50, existing_plan.confidence - 0.10),
            provenance=existing_plan.provenance + [{"fact": f"Falha na etapa {failed_step_id}: {failure_reason}", "origin": "ExecutionRuntime", "type": "FACT"}],
            created_at=utc_iso(),
        )

        replanned_plan.plan_quality_index = self.calculate_pqi(replanned_plan)
        return replanned_plan

    # --- Domain Step Generators (Capability-First) ---

    def _plan_finance_steps(
        self, intent: StructuredIntent, session_context: Dict[str, Any], caps: List[str], agents: List[str]
    ) -> tuple[List[PlanStep], List[Dict[str, Any]], List[Dict[str, Any]]]:
        steps = [
            PlanStep(
                step_id="step_retrieve_fin_ctx",
                objective="Resgatar histórico financeiro e perfil de investimento aprovado do usuário",
                action_type="retrieve",
                inputs={"session_context": session_context},
                expected_output="Perfil financeiro e restrições de liquidez consolidados.",
                dependencies=[],
                required_capabilities=["retrieval.financial_context"],
                candidate_agents=[a for a in agents if a in ["atlas", "financial_agent", "core_agent"]],
                risk_level="low",
                reversibility="reversible",
                requires_confirmation=False,
                validation=["Perfil financeiro possui objetivo e nível de risco descritos."],
            ),
            PlanStep(
                step_id="step_analyze_constraints",
                objective="Analisar restrições orçamentárias, prazo e perfil de risco",
                action_type="analyze",
                inputs={"amount": "23.500", "currency": "BRL"},
                expected_output="Matriz de restrições de alocação de ativos.",
                dependencies=["step_retrieve_fin_ctx"],
                required_capabilities=["modeling.allocation_scenarios"],
                candidate_agents=[a for a in agents if a in ["atlas", "financial_agent"]],
                risk_level="low",
                reversibility="reversible",
                requires_confirmation=False,
                validation=["Todas as restrições foram categorizadas."],
            ),
            PlanStep(
                step_id="step_calculate_allocation",
                objective="Calcular cenários hipotéticos de alocação de ativos (ex: CDB, Renda Fixa, TD)",
                action_type="calculate",
                inputs={"capital": 23500},
                expected_output="Cenários comparativos de rentabilidade e liquidez.",
                dependencies=["step_analyze_constraints"],
                required_capabilities=["modeling.allocation_scenarios"],
                candidate_agents=[a for a in agents if a in ["atlas", "financial_agent"]],
                risk_level="low",
                reversibility="reversible",
                requires_confirmation=False,
                validation=["Cenários cobrem rentabilidade estimada sem promessa garantida irrelevante."],
            ),
            PlanStep(
                step_id="step_evaluate_risk",
                objective="Avaliar riscos de mercado, liquidez e crédito para cada cenário",
                action_type="analyze",
                inputs={},
                expected_output="Relatório de sensibilidade e mitigação de risco.",
                dependencies=["step_calculate_allocation"],
                required_capabilities=["analysis.risk_evaluation"],
                candidate_agents=[a for a in agents if a in ["atlas", "financial_agent"]],
                risk_level="medium",
                reversibility="reversible",
                requires_confirmation=False,
                validation=["Pontos de risco identificados para cada produto de investimento."],
            ),
            PlanStep(
                step_id="step_synthesize_recommendation",
                objective="Sintetizar recomendação fundamentada de alocação de R$ 23.500",
                action_type="synthesize",
                inputs={},
                expected_output="Proposta de alocação de investimento em linguagem clara.",
                dependencies=["step_evaluate_risk"],
                required_capabilities=["synthesis.recommendation"],
                candidate_agents=[a for a in agents if a in ["atlas", "financial_agent", "logos"]],
                risk_level="low",
                reversibility="reversible",
                requires_confirmation=False,
                validation=["Recomendação alinhada com o perfil e objetivo declarados."],
            ),
            PlanStep(
                step_id="step_validate_against_goal",
                objective="Validar proposta final em relação aos objetivos de investimento do usuário",
                action_type="validate",
                inputs={},
                expected_output="Relatório de conformidade da recomendação.",
                dependencies=["step_synthesize_recommendation"],
                required_capabilities=["validation.goal_alignment"],
                candidate_agents=[a for a in agents if a in ["logos", "core_agent"]],
                risk_level="low",
                reversibility="reversible",
                requires_confirmation=False,
                validation=["Nenhum conflito com a declaração do usuário."],
            ),
        ]

        deps = [{"from": s.step_id, "to": dep} for s in steps for dep in s.dependencies]
        confirmation_points = []  # No execution / movement of money, pure advisory plan
        return steps, deps, confirmation_points

    def _plan_communication_steps(
        self, intent: StructuredIntent, caps: List[str], agents: List[str]
    ) -> tuple[List[PlanStep], List[Dict[str, Any]], List[Dict[str, Any]]]:
        steps = [
            PlanStep(
                step_id="step_draft_communication",
                objective="Redigir rascunho de comunicação / e-mail com base na mensagem do usuário",
                action_type="draft",
                inputs={"prompt": intent.raw_input},
                expected_output="Texto do e-mail redigido para revisão.",
                dependencies=[],
                required_capabilities=["external.communication"],
                candidate_agents=[a for a in agents if a in ["logos", "core_agent"]],
                risk_level="low",
                reversibility="reversible",
                requires_confirmation=False,
                validation=["Texto do e-mail reflete a intenção e tom desejado."],
            ),
            PlanStep(
                step_id="step_user_confirmation_gate",
                objective="Solicitar confirmação explícita do usuário antes de enviar e-mail para destinatário externo",
                action_type="user_confirmation",
                inputs={"draft_step": "step_draft_communication"},
                expected_output="Aprovação explícita do usuário para envio de e-mail.",
                dependencies=["step_draft_communication"],
                required_capabilities=["external.communication"],
                candidate_agents=[a for a in agents if a in ["core_agent"]],
                risk_level="high",
                reversibility="irreversible",
                requires_confirmation=True,
                validation=["Usuário autorizou expressamente o envio."],
            ),
            PlanStep(
                step_id="step_send_communication",
                objective="Transmitir e-mail ao destinatário após autorização expressa",
                action_type="external_action",
                inputs={"confirmation_step": "step_user_confirmation_gate"},
                expected_output="Confirmação de transmissão do e-mail.",
                dependencies=["step_user_confirmation_gate"],
                required_capabilities=["external.communication"],
                candidate_agents=[a for a in agents if a in ["core_agent"]],
                risk_level="critical",
                reversibility="irreversible",
                requires_confirmation=True,
                validation=["E-mail enviado com comprovante de entrega."],
            ),
        ]

        deps = [{"from": s.step_id, "to": dep} for s in steps for dep in s.dependencies]
        confirmation_points = [
            {
                "gate_id": "gate_email_dispatch",
                "step_id": "step_user_confirmation_gate",
                "type": "irreversible_external_action",
                "reason": "Envio de e-mail a terceiro produz efeito externo irreversível.",
                "action": "enviar_email",
            }
        ]
        return steps, deps, confirmation_points

    def _plan_comparative_research_steps(
        self, intent: StructuredIntent, caps: List[str], agents: List[str]
    ) -> tuple[List[PlanStep], List[Dict[str, Any]], List[Dict[str, Any]]]:
        # Case D: Demonstrate parallel execution steps
        steps = [
            PlanStep(
                step_id="step_research_alt_1",
                objective="Pesquisar e analisar Alternativa A em profundidade",
                action_type="research",
                inputs={"subject": "Alternative A"},
                expected_output="Relatório técnico/funcional da Alternativa A.",
                dependencies=[],
                required_capabilities=["research.information_gathering"],
                candidate_agents=[a for a in agents if a in ["atlas", "core_agent"]],
                risk_level="low",
                reversibility="reversible",
                requires_confirmation=False,
                validation=["Dados da Alternativa A levantados."],
            ),
            PlanStep(
                step_id="step_research_alt_2",
                objective="Pesquisar e analisar Alternativa B em profundidade",
                action_type="research",
                inputs={"subject": "Alternative B"},
                expected_output="Relatório técnico/funcional da Alternativa B.",
                dependencies=[],  # Runs in PARALLEL with step_research_alt_1
                required_capabilities=["research.information_gathering"],
                candidate_agents=[a for a in agents if a in ["atlas", "core_agent"]],
                risk_level="low",
                reversibility="reversible",
                requires_confirmation=False,
                validation=["Dados da Alternativa B levantados."],
            ),
            PlanStep(
                step_id="step_research_alt_3",
                objective="Pesquisar e analisar Alternativa C em profundidade",
                action_type="research",
                inputs={"subject": "Alternative C"},
                expected_output="Relatório técnico/funcional da Alternativa C.",
                dependencies=[],  # Runs in PARALLEL with alt_1 and alt_2
                required_capabilities=["research.information_gathering"],
                candidate_agents=[a for a in agents if a in ["atlas", "core_agent"]],
                risk_level="low",
                reversibility="reversible",
                requires_confirmation=False,
                validation=["Dados da Alternativa C levantados."],
            ),
            PlanStep(
                step_id="step_compare_alternatives",
                objective="Consolidar matriz comparativa entre Alternativas A, B e C",
                action_type="analyze",
                inputs={},
                expected_output="Matriz comparativa de prós, contras e custos.",
                dependencies=["step_research_alt_1", "step_research_alt_2", "step_research_alt_3"],  # Dependent on all 3 parallel steps
                required_capabilities=["research.comparative_analysis"],
                candidate_agents=[a for a in agents if a in ["logos", "atlas"]],
                risk_level="low",
                reversibility="reversible",
                requires_confirmation=False,
                validation=["Matriz comparativa abrange todas as opções pesquisadas."],
            ),
        ]

        deps = [{"from": s.step_id, "to": dep} for s in steps for dep in s.dependencies]
        return steps, deps, []

    def _plan_software_steps(
        self, intent: StructuredIntent, caps: List[str], agents: List[str]
    ) -> tuple[List[PlanStep], List[Dict[str, Any]], List[Dict[str, Any]]]:
        # Case B: Software creation plan
        steps = [
            PlanStep(
                step_id="step_design_architecture",
                objective="Projetar arquitetura conceitual e modelo de dados para o aplicativo",
                action_type="design",
                inputs={"raw_request": intent.raw_input},
                expected_output="Especificação da arquitetura e entidades principais.",
                dependencies=[],
                required_capabilities=["code.architecture_design"],
                candidate_agents=[a for a in agents if a in ["code_agent", "atlas"]],
                risk_level="low",
                reversibility="reversible",
                requires_confirmation=False,
                validation=["Entidades de dados e módulos principais definidos."],
            ),
            PlanStep(
                step_id="step_generate_scaffold",
                objective="Gerar estrutura de código e rotas básicas do aplicativo",
                action_type="generate_code",
                inputs={"arch_step": "step_design_architecture"},
                expected_output="Estrutura de arquivos e código base sem erros de sintaxe.",
                dependencies=["step_design_architecture"],
                required_capabilities=["code.scaffold_generation"],
                candidate_agents=[a for a in agents if a in ["code_agent"]],
                risk_level="medium",
                reversibility="reversible",
                requires_confirmation=False,
                validation=["Código compila/linta sem erros fatais."],
            ),
            PlanStep(
                step_id="step_verify_functionality",
                objective="Verificar funcionalidades e testes unitários do aplicativo gerado",
                action_type="validate",
                inputs={},
                expected_output="Relatório de testes de compilação e verificação.",
                dependencies=["step_generate_scaffold"],
                required_capabilities=["validation.goal_alignment"],
                candidate_agents=[a for a in agents if a in ["code_agent", "core_agent"]],
                risk_level="low",
                reversibility="reversible",
                requires_confirmation=False,
                validation=["Todos os testes automatizados passaram com sucesso."],
            ),
        ]

        deps = [{"from": s.step_id, "to": dep} for s in steps for dep in s.dependencies]
        return steps, deps, []

    def _plan_generic_steps(
        self, intent: StructuredIntent, caps: List[str], agents: List[str]
    ) -> tuple[List[PlanStep], List[Dict[str, Any]], List[Dict[str, Any]]]:
        steps = [
            PlanStep(
                step_id="step_gather_context",
                objective="Mapear informações essenciais para atender a solicitação do usuário",
                action_type="retrieve",
                inputs={},
                expected_output="Contexto inicial e parâmetros de execução mapeados.",
                dependencies=[],
                required_capabilities=["research.information_gathering"],
                candidate_agents=[a for a in agents if a in ["core_agent"]],
                risk_level="low",
                reversibility="reversible",
                requires_confirmation=False,
                validation=["Parâmetros mapeados."],
            ),
            PlanStep(
                step_id="step_execute_task",
                objective="Executar ação solicitada conforme parâmetros definidos",
                action_type="execute",
                inputs={},
                expected_output="Resultado da tarefa gerado.",
                dependencies=["step_gather_context"],
                required_capabilities=["synthesis.recommendation"],
                candidate_agents=[a for a in agents if a in ["core_agent"]],
                risk_level="low",
                reversibility="reversible",
                requires_confirmation=False,
                validation=["Resultado validado."],
            ),
        ]

        deps = [{"from": s.step_id, "to": dep} for s in steps for dep in s.dependencies]
        return steps, deps, []
